/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class ADD_USU extends javax.swing.JFrame {

    /**
     * Creates new form ADD_USU
     */
    public ADD_USU() {
        initComponents();
        Pais = new DefaultComboBoxModel();
        Pais.addElement("España");
        Pais.addElement("Francia");
        Pais.addElement("Portugal");
        Pais.addElement("Inglaterra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEdad = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsu = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jRadioButtonMA18 = new javax.swing.JRadioButton();
        jRadioButtonME18 = new javax.swing.JRadioButton();
        jRadioButtonH = new javax.swing.JRadioButton();
        jRadioButtonM = new javax.swing.JRadioButton();
        jRadioButtonSD = new javax.swing.JRadioButton();
        jComboBoxPais = new javax.swing.JComboBox<>();
        jToggleButtonADD = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadiendo Ususario\n"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Edad");

        jLabel5.setText("Sexo");

        jLabel6.setText("Pais");

        jTextFieldUsu.setText("Usuario");
        jTextFieldUsu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuFocusLost(evt);
            }
        });

        jTextFieldPass.setText("Contraseña");
        jTextFieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPassFocusLost(evt);
            }
        });
        jTextFieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPassMouseClicked(evt);
            }
        });

        buttonGroupEdad.add(jRadioButtonMA18);
        jRadioButtonMA18.setText("Mayor 18");

        buttonGroupEdad.add(jRadioButtonME18);
        jRadioButtonME18.setText("Menor 18");

        Sexo.add(jRadioButtonH);
        jRadioButtonH.setText("Hombre");

        Sexo.add(jRadioButtonM);
        jRadioButtonM.setText("Mujer");

        Sexo.add(jRadioButtonSD);
        jRadioButtonSD.setText("Sin definir");

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pais:", "España", "Francia", "Portugal", "Inglaterra" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonH)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonM)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonSD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMA18)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonME18))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldUsu)
                        .addComponent(jTextFieldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButtonMA18)
                            .addComponent(jRadioButtonME18))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonH)
                        .addComponent(jRadioButtonM)
                        .addComponent(jRadioButtonSD)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jToggleButtonADD.setText("Añadir Ususario y volver");
        jToggleButtonADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonADDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonADD))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonADD)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuFocusGained
        // TODO add your handling code here:
        jTextFieldUsu.setText("");
    }//GEN-LAST:event_jTextFieldUsuFocusGained

    private void jTextFieldUsuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuFocusLost
        // TODO add your handling code here:
        if (jTextFieldUsu.getText().equalsIgnoreCase("")) {
            jTextFieldUsu.setText("Usuario");
        }
    }//GEN-LAST:event_jTextFieldUsuFocusLost

    private void jTextFieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPassMouseClicked

    }//GEN-LAST:event_jTextFieldPassMouseClicked

    private void jTextFieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassFocusGained
        // TODO add your handling code here:
        jTextFieldPass.setText("");
    }//GEN-LAST:event_jTextFieldPassFocusGained

    private void jTextFieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassFocusLost
        // TODO add your handling code here:
        if (jTextFieldPass.getText().equalsIgnoreCase("")) {
            jTextFieldPass.setText("Contraseña");
        }
    }//GEN-LAST:event_jTextFieldPassFocusLost

    private void jToggleButtonADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonADDMouseClicked
        // TODO add your handling code here:
        String nombre,contraseña, pais;
        int opc=jComboBoxPais.getSelectedIndex();
        if (opc==0) {
            JOptionPane.showMessageDialog(rootPane, "Opcion no vaida por favor selecciona un pais");
        }else{
            nombre=jTextFieldUsu.getText();
            contraseña= jTextFieldPass.getText();
            pais=(String)jComboBoxPais.getSelectedItem();
            Login Lo = new Login(nombre, contraseña);
            Lo.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jToggleButtonADDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_USU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_USU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_USU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_USU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_USU().setVisible(true);
            }
        });
    }
    private javax.swing.DefaultComboBoxModel<String> Pais;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.ButtonGroup buttonGroupEdad;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonH;
    private javax.swing.JRadioButton jRadioButtonM;
    private javax.swing.JRadioButton jRadioButtonMA18;
    private javax.swing.JRadioButton jRadioButtonME18;
    private javax.swing.JRadioButton jRadioButtonSD;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUsu;
    private javax.swing.JToggleButton jToggleButtonADD;
    // End of variables declaration//GEN-END:variables
}
