/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public Login(String contraseña) {
        initComponents();
        Pass = contraseña;
    }
    public Login(String nombre,String contraseña) {
        initComponents();
        Nombre=nombre;
        Pass = contraseña;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelIMG = new javax.swing.JLabel();
        jTextFieldUSU = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jPasswordFieldPASS = new javax.swing.JPasswordField();
        jToggleButtonResPass = new javax.swing.JToggleButton();
        jToggleButtonADDUSU = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a esta aplicacion");

        jLabelIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\marco\\Downloads\\descarga.jpg")); // NOI18N

        jTextFieldUSU.setText("Usuario");
        jTextFieldUSU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUSUFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUSUFocusLost(evt);
            }
        });

        jButtonGuardar.setText("Entrar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });

        jPasswordFieldPASS.setText("Contraseña");
        jPasswordFieldPASS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPASSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPASSFocusLost(evt);
            }
        });

        jToggleButtonResPass.setText("Restaurar contraseña");
        jToggleButtonResPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonResPassMouseClicked(evt);
            }
        });

        jToggleButtonADDUSU.setText("Añadir Ususario");
        jToggleButtonADDUSU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonADDUSUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addComponent(jLabelIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jTextFieldUSU)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPASS)
                    .addComponent(jToggleButtonResPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonADDUSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldUSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonResPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonADDUSU)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUSUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUSUFocusGained
        // TODO add your handling code here:
        jTextFieldUSU.setText("");
    }//GEN-LAST:event_jTextFieldUSUFocusGained

    private void jTextFieldUSUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUSUFocusLost
        // TODO add your handling code here:
        if (jTextFieldUSU.getText().equalsIgnoreCase("")) {
            jTextFieldUSU.setText("Usuario");
        }
    }//GEN-LAST:event_jTextFieldUSUFocusLost

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        // TODO add your handling code here:
       String nombre, password="";
        char[] pass;
        
        
        nombre = jTextFieldUSU.getText();
        pass = jPasswordFieldPASS.getPassword();
        
        for (char pas : pass) {
            password+=pas;
        }
        
        if (nombre.equals(this.Nombre) && password.equals(this.Pass)){
            Inicio ini = new Inicio(nombre,password);
            ini.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrectos");
            jTextFieldUSU.setText("Usuario");
            jPasswordFieldPASS.setText("");
        }
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jPasswordFieldPASSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPASSFocusGained
        // TODO add your handling code here:
        jPasswordFieldPASS.setText("");
    }//GEN-LAST:event_jPasswordFieldPASSFocusGained

    private void jPasswordFieldPASSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPASSFocusLost
        // TODO add your handling code here:
        if (jPasswordFieldPASS.getPassword().equals("")) {
            jPasswordFieldPASS.setText("Contraseña");
        }
    }//GEN-LAST:event_jPasswordFieldPASSFocusLost

    private void jToggleButtonResPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonResPassMouseClicked
        // TODO add your handling code here:
        
        Res_Pass RP = new Res_Pass(Nombre,Pass);
        RP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonResPassMouseClicked

    private void jToggleButtonADDUSUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonADDUSUMouseClicked
        // TODO add your handling code here:
        ADD_USU AD = new ADD_USU();
        AD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonADDUSUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private String Nombre = "Admin";
    private String Pass = "Admin1234";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIMG;
    private javax.swing.JPasswordField jPasswordFieldPASS;
    private javax.swing.JTextField jTextFieldUSU;
    private javax.swing.JToggleButton jToggleButtonADDUSU;
    private javax.swing.JToggleButton jToggleButtonResPass;
    // End of variables declaration//GEN-END:variables
}
