/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author marco
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        modeloLis=new DefaultListModel();
        modeloLis.addElement("Pan");
        modeloLis.addElement("Leche");
        jListPRO.setModel(modeloLis);
        
        modeloBUS = new DefaultListModel();
        
        setIconImage(new ImageIcon(getClass().getResource("Hear2001.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPRODUCTO = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBUS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPRO = new javax.swing.JList<>();
        jButtonDELETE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Producto");

        jTextFieldPRODUCTO.setText("Producto");
        jTextFieldPRODUCTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPRODUCTOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPRODUCTOFocusLost(evt);
            }
        });
        jTextFieldPRODUCTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPRODUCTOMouseClicked(evt);
            }
        });

        jButtonADD.setText("Añadir");
        jButtonADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonADDMouseClicked(evt);
            }
        });

        jLabel2.setText("Informacion");

        jTextFieldBUS.setText("Buscar producto");
        jTextFieldBUS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBUSFocusGained(evt);
            }
        });
        jTextFieldBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBUSActionPerformed(evt);
            }
        });
        jTextFieldBUS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBUSKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jListPRO);

        jButtonDELETE.setText("Borrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonADD))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBUS)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonDELETE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDELETE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonADD))
                    .addComponent(jScrollPane1))
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPRODUCTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPRODUCTOMouseClicked
        // TODO add your handling code here:
        jTextFieldPRODUCTO.setText("");
    }//GEN-LAST:event_jTextFieldPRODUCTOMouseClicked

    private void jTextFieldPRODUCTOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPRODUCTOFocusGained
        // TODO add your handling code here:
        jTextFieldPRODUCTO.setText("");
    }//GEN-LAST:event_jTextFieldPRODUCTOFocusGained

    private void jTextFieldPRODUCTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPRODUCTOFocusLost
        // TODO add your handling code here:
        if (jTextFieldPRODUCTO.getText().equalsIgnoreCase("")) {
         jTextFieldPRODUCTO.setText("Producto");
        }
    }//GEN-LAST:event_jTextFieldPRODUCTOFocusLost

    private void jButtonADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonADDMouseClicked
        // TODO add your handling code here:
        
        String producto;
        
        producto=jTextFieldPRODUCTO.getText();
        
        modeloLis.addElement(producto);
        
        jTextFieldPRODUCTO.setText("Producto");
        
    }//GEN-LAST:event_jButtonADDMouseClicked

    private void jTextFieldBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBUSActionPerformed

    private void jTextFieldBUSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBUSFocusGained
        // TODO add your handling code here:
        jTextFieldBUS.setText("");
    }//GEN-LAST:event_jTextFieldBUSFocusGained

    private void jTextFieldBUSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBUSKeyReleased
        // TODO add your handling code here:
        
        String producto;
        
        producto=jTextFieldBUS.getText();
        
        for (int i = 0; i < modeloLis.getSize(); i++) {
            if (modeloLis.get(i).startsWith(producto)) {
                System.out.println(modeloLis.getElementAt(i));
                modeloBUS.addElement(modeloLis.getElementAt(i));
                break;
            }
        }
        jListPRO.setModel(modeloBUS);
    }//GEN-LAST:event_jTextFieldBUSKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private javax.swing.DefaultListModel<String> modeloLis;
    private javax.swing.DefaultListModel<String> modeloBUS;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListPRO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBUS;
    private javax.swing.JTextField jTextFieldPRODUCTO;
    // End of variables declaration//GEN-END:variables
}
